What is the causal effect of quitting smoking (qsmk = 1) on weight gain by 1982 (wt82), adjusting for confounders using propensity score matching?

In [113]:
from causallib.datasets import load_nhefs
import pandas as pd
from sklearn.linear_model import LogisticRegression
import numpy as np
from pymatch.Matcher import Matcher
from sklearn.neighbors import NearestNeighbors
import altair as alt
from scipy import stats

pd.set_option('display.max_columns', None)

load data

In [2]:
# Load the dataset
data = load_nhefs()

# Access data, treatment, outcome, and features
X, a, y = data.X, data.a, data.y
dfFull = pd.concat([X,a, y], axis= 1)

In [3]:
dfFull.head()

,age,race,sex,smokeintensity,smokeyrs,wt71,active_1,active_2,education_2,education_3,education_4,education_5,exercise_1,exercise_2,age^2,wt71^2,smokeintensity^2,smokeyrs^2,qsmk,wt82_71
0,42,1,0,30,29,79.04,0,0,0,0,0,0,0,1,1764,6247.3216,900,841,0,-10.093960
1,36,0,0,20,24,58.63,0,0,1,0,0,0,0,0,1296,3437.4769,400,576,0,2.604970
2,56,1,1,20,26,56.81,0,0,1,0,0,0,0,1,3136,3227.3761,400,676,0,9.414486
3,68,1,0,3,53,59.42,1,0,0,0,0,0,0,1,4624,3530.7364,9,2809,0,4.990117
4,40,0,0,20,19,87.09,1,0,1,0,0,0,1,0,1600,7584.6681,400,361,0,4.989251

In [4]:
X.head()

,age,race,sex,smokeintensity,smokeyrs,wt71,active_1,active_2,education_2,education_3,education_4,education_5,exercise_1,exercise_2,age^2,wt71^2,smokeintensity^2,smokeyrs^2
0,42,1,0,30,29,79.04,0,0,0,0,0,0,0,1,1764,6247.3216,900,841
1,36,0,0,20,24,58.63,0,0,1,0,0,0,0,0,1296,3437.4769,400,576
2,56,1,1,20,26,56.81,0,0,1,0,0,0,0,1,3136,3227.3761,400,676
3,68,1,0,3,53,59.42,1,0,0,0,0,0,0,1,4624,3530.7364,9,2809
4,40,0,0,20,19,87.09,1,0,1,0,0,0,1,0,1600,7584.6681,400,361

In [5]:
y.head()

0   -10.093960
1     2.604970
2     9.414486
3     4.990117
4     4.989251
Name: wt82_71, dtype: float64

In [6]:
a.head()

0    0
1    0
2    0
3    0
4    0
Name: qsmk, dtype: int64

In [7]:
dfFull.head()

,age,race,sex,smokeintensity,smokeyrs,wt71,active_1,active_2,education_2,education_3,education_4,education_5,exercise_1,exercise_2,age^2,wt71^2,smokeintensity^2,smokeyrs^2,qsmk,wt82_71
0,42,1,0,30,29,79.04,0,0,0,0,0,0,0,1,1764,6247.3216,900,841,0,-10.093960
1,36,0,0,20,24,58.63,0,0,1,0,0,0,0,0,1296,3437.4769,400,576,0,2.604970
2,56,1,1,20,26,56.81,0,0,1,0,0,0,0,1,3136,3227.3761,400,676,0,9.414486
3,68,1,0,3,53,59.42,1,0,0,0,0,0,0,1,4624,3530.7364,9,2809,0,4.990117
4,40,0,0,20,19,87.09,1,0,1,0,0,0,1,0,1600,7584.6681,400,361,0,4.989251

convert true/false

In [8]:
cols = ['active_1', 'active_2', 'education_2','education_3','education_4', 'education_5', 'exercise_1', 'exercise_2']

def convertTrueFalse(df, cols):

    df_new = df.copy()

    for c in cols:
        df_new[c] = np.where(df_new[c] == True, 1, 0)
    

    return df_new

In [9]:
X = convertTrueFalse(X, cols)

define treatment, outcome, covariates

In [12]:
treat = 'qsmk'
outcome = 'wt82_71'

covs = [
        'age'
        ,'race'
        ,'sex'
        ,'smokeintensity'
        ,'smokeyrs' 
        ,'wt71'
        ,'active_2'
        ,'education_5'
        ,'exercise_2'
        ]

estimate propensity scores

In [13]:
logit = LogisticRegression(max_iter=2000)
logit.fit(dfFull[covs], dfFull[treat])

LogisticRegression(max_iter=2000)

In [14]:
dfFull['pscore'] = logit.predict_proba(dfFull[covs])[:,1]

perform matching

In [17]:
test = dfFull[dfFull[treat]==1]
control = dfFull[dfFull[treat]==0]

In [40]:
nn = NearestNeighbors(n_neighbors=1, algorithm='ball_tree')
nn.fit(control[['pscore']])

NearestNeighbors(algorithm='ball_tree', n_neighbors=1)

In [41]:
distances, indices = nn.kneighbors(test[['pscore']])

In [45]:
matched_control = control.iloc[indices.flatten()]
matched_df = pd.concat([test, matched_control])

plots

In [ ]:
def standarized_mean_difference(
                                data
                                ,covars
                                ,treat=treat
                                ):
     
    treated = data[data[treat] == 1]
    control = data[data[treat] == 0]
     
    result = pd.DataFrame()

    smds = []
    treatedMeans = []
    controlMeans = []

    for var in covars:
        mean_treated = treated[var].mean()
        treatedMeans = treatedMeans + [mean_treated]

        mean_control = control[var].mean()
        controlMeans = controlMeans + [mean_control]

        sd_treated = treated[var].std()
        sd_control = control[var].std()

        # smd[var] = abs(mean_treated - mean_control) / np.sqrt((sd_treated**2 + sd_control**2) / 2)
        smd = abs(mean_treated - mean_control) / np.sqrt((sd_treated**2 + sd_control**2) / 2)

        smds = smds + [smd]
    
    result['variable'] = covars
    result['treated mean'] = treatedMeans
    result['control mean'] = controlMeans
    result['standardized mean difference'] = smds
         
    return result


def proportion_difference(
                                data
                                ,covars
                                ,treat=treat
                                ):
     
    treated = data[data[treat] == 1]
    control = data[data[treat] == 0]
     
    result = pd.DataFrame()

    diffs = []
    treatedMeans = []
    controlMeans = []

    for var in covars:
        mean_treated = treated[var].mean()
        treatedMeans = treatedMeans + [mean_treated]

        mean_control = control[var].mean()
        controlMeans = controlMeans + [mean_control]

        sd_treated = treated[var].std()
        sd_control = control[var].std()

        diff = abs(mean_treated - mean_control)

        diffs = diffs + [diff]
    
    result['variable'] = covars
    result['treated mean'] = treatedMeans
    result['control mean'] = controlMeans
    result['mean difference'] = diffs
         
    return result

In [96]:
smd_before_matching = standarized_mean_difference(dfFull, ['age', 'smokeintensity', 'smokeyrs', 'wt71'])
smd_before_matching['before_after'] = 'before'

smd_after_matching = standarized_mean_difference(matched_df, ['age', 'smokeintensity', 'smokeyrs', 'wt71'])
smd_after_matching['before_after'] = 'after'

beforeAfter = pd.concat([smd_before_matching,smd_after_matching])

In [99]:
beforeAfter

,variable,treated mean,control mean,standardized mean difference,before_after
0,age,46.173697,42.788478,0.281981,before
1,smokeintensity,18.602978,21.191745,0.216675,before
2,smokeyrs,26.032258,24.087704,0.158918,before
3,wt71,72.354888,70.302837,0.133216,before
0,age,46.173697,45.143921,0.084403,after
1,smokeintensity,18.602978,18.181141,0.037500,after
2,smokeyrs,26.032258,24.483871,0.124576,after
3,wt71,72.354888,72.602060,0.015958,after

In [100]:
chart = alt.Chart(beforeAfter).mark_circle(size=100).encode(
                x='standardized mean difference',
                y=alt.Y('variable:N', axis=alt.Axis(grid=True)),
                color=alt.Color('before_after:N', legend=alt.Legend(title=None))
            ).properties(
                title='Before and After',
                height=200
            )\
            .configure_axis(grid=False)

chart

alt.Chart(...)

In [106]:
smd_before_matching = proportion_difference(dfFull, ['race', 'sex', 'active_2', 'education_5', 'exercise_2'])
smd_before_matching['before_after'] = 'before'

smd_after_matching = proportion_difference(matched_df, ['race', 'sex', 'active_2', 'education_5', 'exercise_2'])
smd_after_matching['before_after'] = 'after'

beforeAfter = pd.concat([smd_before_matching,smd_after_matching])

In [107]:
beforeAfter

      variable  treated mean  control mean  mean difference before_after
0         race      0.089330      0.146174         0.056844       before
1          sex      0.454094      0.533964         0.079870       before
2     active_2      0.111663      0.089424         0.022239       before
3  education_5      0.153846      0.098882         0.054964       before
4   exercise_2      0.406948      0.379192         0.027756       before
0         race      0.089330      0.104218         0.014888        after
1          sex      0.454094      0.481390         0.027295        after
2     active_2      0.111663      0.084367         0.027295        after
3  education_5      0.153846      0.198511         0.044665        after
4   exercise_2      0.406948      0.397022         0.009926        after

In [108]:
chart = alt.Chart(beforeAfter).mark_circle(size=100).encode(
                x='mean difference',
                y=alt.Y('variable:N', axis=alt.Axis(grid=True)),
                color=alt.Color('before_after:N', legend=alt.Legend(title=None))
            ).properties(
                title='Before and After',
                height=200
            )\
            .configure_axis(grid=False)

chart

alt.Chart(...)

estimate att

In [112]:
treated = matched_df[matched_df[treat] == 1]
control = matched_df[matched_df[treat] == 0]

att = treated[outcome].mean() - control[outcome].mean()
att

3.108292318957817

In [116]:
stats.ttest_ind(treated[outcome], control[outcome], equal_var=False)

TtestResult(statistic=5.719201976564839, pvalue=1.5508527289774764e-08, df=743.2613043809507)